from config import CELL_SIZE, GRID_WIDTH, GRID_HEIGHT

TANK_GROUP_SIZE = 12
INFANTRY_GROUP_SIZE = 12
ARTILLERY_GROUP_SIZE = 3
ANTI_TANK_GROUP_SIZE = 2

ENEMY_TANK_GROUP_SIZE = 4
ENEMY_INFANTRY_GROUP_SIZE = 4
ENEMY_ANTI_TANK_GROUP_SIZE = 2
ENEMY_ARTILLERY_GROUP_SIZE = 1

tank_state_template = {
    "type": "tank",
    "position": (0, GRID_HEIGHT),
    # "position": (45, 25),
    "facing": (0, 1),
    "speed": (((75 / 3.6) * 6) / CELL_SIZE),
    "move_credit": 0,
    "base_health": 20,
    "health": 20 * TANK_GROUP_SIZE,
    "max_health": 20 * TANK_GROUP_SIZE,
    "group_size": TANK_GROUP_SIZE,
    "current_group_size": TANK_GROUP_SIZE,
    "cumulative_damage": 0.0,
    "armor_front": 17,
    "armor_side": 4,
    "armor_rear": 3,
    "friendly_accuracy": 0.75,
    "base_rate_of_fire": 4.9,
    "damage": 9,
    "suppression": 0.12,
    "penetration": 18,
    "vision_range": 2000 / CELL_SIZE,
    "attack_range": 1200 / CELL_SIZE,
    "all_enemies_spotted": False,
    "total_enemies": 2,
    "suppression_from_enemy": 0.0,
    "scout_steps": 0,
    "stealth_modifier": 0
}
infantry_state_template = {
    "type": "infantry",
    "position": (1, GRID_HEIGHT),
    # "position": (45, 26),
    "facing": (0, 1),
    "speed": (((65 / 3.6) * 6) / CELL_SIZE),
    "move_credit": 0,
    "base_health": 1,
    "health": 1 * INFANTRY_GROUP_SIZE,
    "max_health": 1 * INFANTRY_GROUP_SIZE,
    "group_size": INFANTRY_GROUP_SIZE,
    "current_group_size": INFANTRY_GROUP_SIZE,
    "cumulative_damage": 0.0,
    "armor_front": 0,
    "armor_side": 0,
    "armor_rear": 0,
    "friendly_accuracy": 0.50,
    "base_rate_of_fire": 294,
    "damage": 0.8,
    "suppression": 0.01,
    "penetration": 1,
    "vision_range": 2200 / CELL_SIZE,
    "attack_range": 600 / CELL_SIZE,
    "all_enemies_spotted": False,
    "total_enemies": 2,
    "suppression_from_enemy": 0.0,
    "scout_steps": 0,
    "stealth_modifier": 0
}
artillery_state_template = {
    "type": "artillery",
    "position": (2, GRID_HEIGHT),
    # "position": (47, 27),
    "facing": (0, 1),
    "speed": (((65 / 3.6) * 6) / CELL_SIZE),
    "move_credit": 0,
    "base_health": 18,
    "health": 18 * ARTILLERY_GROUP_SIZE,
    "max_health": 18 * ARTILLERY_GROUP_SIZE,
    "group_size": ARTILLERY_GROUP_SIZE,
    "current_group_size": ARTILLERY_GROUP_SIZE,
    "cumulative_damage": 0.0,
    "armor_front": 2,
    "armor_side": 1,
    "armor_rear": 1,
    "friendly_accuracy": 0.85,
    "base_rate_of_fire": 8.6,
    "damage": 3.5,
    "suppression": 15,
    "penetration": 1,
    "vision_range": 1800 / CELL_SIZE,
    "attack_range": 2000 / CELL_SIZE,
    "all_enemies_spotted": False,
    "total_enemies": 2,
    "suppression_from_enemy": 0.0,
    "scout_steps": 0,
    "stealth_modifier": 0
}
anti_tank_state_template = {
    "type": "anti-tank",
    "position": (3, GRID_HEIGHT),
    # "position": (49, 28),
    "facing": (0, 1),
    "speed": (((65 / 3.6) * 6) / CELL_SIZE),
    "move_credit": 0,
    "base_health": 18,
    "health": 18 * ANTI_TANK_GROUP_SIZE,
    "max_health": 18 * ANTI_TANK_GROUP_SIZE,
    "group_size": ANTI_TANK_GROUP_SIZE,
    "current_group_size": ANTI_TANK_GROUP_SIZE,
    "cumulative_damage": 0.0,
    "armor_front": 2,
    "armor_side": 1,
    "armor_rear": 1,
    "friendly_accuracy": 0.90,
    "base_rate_of_fire": 6.3,
    "damage": 15,
    "suppression": 0.10,
    "penetration": 22,
    "vision_range": 2000 / CELL_SIZE,
    "attack_range": 1400 / CELL_SIZE,
    "all_enemies_spotted": False,
    "total_enemies": 2,
    "suppression_from_enemy": 0.0,
    "scout_steps": 0,
    "stealth_modifier": 50
}
enemy_tank_state_template = {
    "type": "enemy_tank",
    "position": (GRID_WIDTH, 1),
    "facing": (0, 1),
    "speed": (((85 / 3.6) * 6) / CELL_SIZE),
    "move_credit": 0,
    "enemy_alive": True,
    "health": 25 * ENEMY_TANK_GROUP_SIZE,
    "max_health": 25 * ENEMY_TANK_GROUP_SIZE,
    "base_health": 25,
    "group_size": ENEMY_TANK_GROUP_SIZE,
    "current_group_size": ENEMY_TANK_GROUP_SIZE,
    "cumulative_damage": 0.0,
    "armor_front": 18,
    "armor_side": 5,
    "armor_rear": 3,
    "outpost_position": (GRID_WIDTH - 1, 0),
    "outpost_secured": False,
    "attack_range": 1200 / CELL_SIZE,
    "accuracy": 0.7,
    "penetration": 18,
    "damage": 9,
    "suppression": 0.12,
    "base_rate_of_fire": 5.5,
    "suppression_from_enemy": 0.0,
    "patrol_points": [],
    "current_patrol_index": 0,
    "vision_range": 1800 / CELL_SIZE,
    "retreat_point": (GRID_WIDTH - 1, GRID_HEIGHT - 1),
    "stealth_modifier": 0
}
enemy_infantry_state_template = {
    "type": "infantry",
    "position": (GRID_WIDTH - 1, 1),
    "facing": (0, 1),
    "speed": (((75 / 3.6) * 6) / CELL_SIZE),
    "move_credit": 0,
    "enemy_alive": True,
    "base_health": 1,
    "health": 1 * ENEMY_INFANTRY_GROUP_SIZE,
    "max_health": 1 * ENEMY_INFANTRY_GROUP_SIZE,
    "group_size": ENEMY_INFANTRY_GROUP_SIZE,
    "current_group_size": ENEMY_INFANTRY_GROUP_SIZE,
    "cumulative_damage": 0.0,
    "armor_front": 0,
    "armor_side": 0,
    "armor_rear": 0,
    "outpost_position": (GRID_WIDTH - 1, 0),
    "outpost_secured": False,
    "accuracy": 0.50,
    "base_rate_of_fire": 294,
    "damage": 0.8,
    "suppression": 0.01,
    "penetration": 1,
    "attack_range": 600 / CELL_SIZE,
    "all_enemies_spotted": False,
    "total_enemies": 2,
    "suppression_from_enemy": 0.0,
    "patrol_points": [],
    "current_patrol_index": 0,
    "vision_range": 2000 / CELL_SIZE,
    "scout_steps": 0,
    "stealth_modifier": 0
}
enemy_anti_tank_state_template = {
    "type": "anti-tank",
    "position": (GRID_WIDTH - 2, 1),
    "facing": (0, 1),
    "speed": (((75 / 3.6) * 6) / CELL_SIZE),
    "move_credit": 0,
    "enemy_alive": True,
    "base_health": 18,
    "health": 18 * ENEMY_ANTI_TANK_GROUP_SIZE,
    "max_health": 18 * ENEMY_ANTI_TANK_GROUP_SIZE,
    "group_size": ENEMY_ANTI_TANK_GROUP_SIZE,
    "current_group_size": ENEMY_ANTI_TANK_GROUP_SIZE,
    "cumulative_damage": 0.0,
    "armor_front": 2,
    "armor_side": 1,
    "armor_rear": 1,
    "outpost_position": (GRID_WIDTH - 1, 0),
    "outpost_secured": False,
    "accuracy": 0.90,
    "base_rate_of_fire": 6.3,
    "damage": 15,
    "suppression": 0.1,
    "penetration": 22,
    "attack_range": 1400 / CELL_SIZE,
    "all_enemies_spotted": False,
    "total_enemies": 2,
    "suppression_from_enemy": 0.0,
    "patrol_points": [],
    "current_patrol_index": 0,
    "vision_range": 2000 / CELL_SIZE,
    "scout_steps": 0,
    "stealth_modifier": 50
}
enemy_artillery_state_template = {
    "type": "artillery",
    "position": (GRID_WIDTH - 3, 1),
    "facing": (0, 1),
    "speed": (((75 / 3.6) * 6) / CELL_SIZE),
    "move_credit": 0,
    "enemy_alive": True,
    "base_health": 13,
    "health": 13 * ENEMY_ANTI_TANK_GROUP_SIZE,
    "max_health": 13 * ENEMY_ANTI_TANK_GROUP_SIZE,
    "group_size": ENEMY_ANTI_TANK_GROUP_SIZE,
    "current_group_size": ENEMY_ANTI_TANK_GROUP_SIZE,
    "cumulative_damage": 0.0,
    "armor_front": 2,
    "armor_side": 1,
    "armor_rear": 1,
    "outpost_position": (GRID_WIDTH - 1, 0),
    "outpost_secured": False,
    "accuracy": 0.90,
    "base_rate_of_fire": 8.6,
    "damage": 3.5,
    "suppression": 0.15,
    "penetration": 0,
    "attack_range": 2200 / CELL_SIZE,
    "all_enemies_spotted": False,
    "total_enemies": 2,
    "suppression_from_enemy": 0.0,
    "patrol_points": [],
    "current_patrol_index": 0,
    "vision_range": 1800 / CELL_SIZE,
    "scout_steps": 0,
    "stealth_modifier": 0
}

__all__ = [
"tank_state_template",
"infantry_state_template",
"artillery_state_template",
"scout_state_template",
"anti_tank_state_template",
"enemy_tank_state_template",
"enemy_infantry_state_template",
"enemy_anti_tank_state_template",
"enemy_artillery_state_template"
]
